# set(MCPU_FLAGS "-mthumb -mcpu=cortex-m4")
# set(VFP_FLAGS "-mfloat-abi=hard -mfpu=fpv4-sp-d16")

set(CMAKE_SYSTEM_NAME Generic)
set(CMAKE_SYSTEM_PROCESSOR ARM)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

if(WIN32)
    set(TOOLCHAIN_EXT ".exe")
else()
    set(TOOLCHAIN_EXT "")
endif(WIN32)

set(TOOLCHAIN_DIR "E:/00_ARM/gcc-arm-11.2-2022.02-mingw-w64-i686-arm-none-eabi/bin")
set(BINUTILS_PATH ${TOOLCHAIN_DIR})
set(TOOLCHAIN_PREFIX ${TOOLCHAIN_DIR}/arm-none-eabi-)

set(CMAKE_C_COMPILER   ${TOOLCHAIN_PREFIX}gcc${TOOLCHAIN_EXT})
set(CMAKE_CXX_COMPILER ${TOOLCHAIN_PREFIX}g++${TOOLCHAIN_EXT})
set(CMAKE_ASM_COMPILER ${TOOLCHAIN_PREFIX}gcc${TOOLCHAIN_EXT})
set(CMAKE_LINKER       ${TOOLCHAIN_PREFIX}gcc${TOOLCHAIN_EXT})
set(CMAKE_SIZE_UTIL    ${TOOLCHAIN_PREFIX}size${TOOLCHAIN_EXT} CACHE INTERNAL "size tool")
set(CMAKE_OBJCOPY      ${TOOLCHAIN_PREFIX}objcopy${TOOLCHAIN_EXT} CACHE INTERNAL "objcopy tool")
set(CMAKE_OBJDUMP      ${TOOLCHAIN_PREFIX}objdump${TOOLCHAIN_EXT})
set(CMAKE_NM_UTIL      ${TOOLCHAIN_PREFIX}gcc-nm${TOOLCHAIN_EXT})
set(CMAKE_AR           ${TOOLCHAIN_PREFIX}gcc-ar${TOOLCHAIN_EXT})
set(CMAKE_RANLIB       ${TOOLCHAIN_PREFIX}gcc-ranlib${TOOLCHAIN_EXT})

set(CMAKE_FIND_ROOT_PATH ${BINUTILS_PATH})
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

# set(CMAKE_COMMON_FLAGS "-g3 -ffunction-sections -fdata-sections -fno-strict-aliasing -fno-builtin -fno-common -Wall -Wshadow -Wdouble-promotion -Werror")

# set(CMAKE_C_FLAGS "${MCPU_FLAGS} ${VFP_FLAGS} ${CMAKE_COMMON_FLAGS}")
# set(CMAKE_CXX_FLAGS "${MCPU_FLAGS} ${VFP_FLAGS} ${CMAKE_COMMON_FLAGS}")
# set(CMAKE_ASM_FLAGS "${MCPU_FLAGS} ${VFP_FLAGS} ${CMAKE_COMMON_FLAGS}")
# set(CMAKE_EXE_LINKER_FLAGS "${LD_FLAGS} --specs=nano.specs -Wl,--gc-sections,-print-memory-usage")

# set(CMAKE_C_FLAGS_DEBUG "-O0")
# set(CMAKE_CXX_ASM_FLAGS_DEBUG "-O0")
# set(CMAKE_ASM_FLAGS_DEBUG "")
# set(CMAKE_EXE_LINKER_FLAGS_DEBUG "")

# set(CMAKE_C_FLAGS_RELEASE "-Os -flto")
# set(CMAKE_CXX_FLAGS_RELEASE "-Os -flto")
# set(CMAKE_ASM_FLAGS_RELEASE "")
# set(CMAKE_EXE_LINKER_FLAGS_RELEASE "-flto")
